### ISSUE TITLE
DatePicker as an option to a column in a new row. 

### ISSUE THREAD

**Issue by Emmaalara** [CrossroadsCX/datatable#45]
I am thinking about this specific use case: 

<img width="1391" alt="Captura de Pantalla 2021-10-29 a la(s) 11 07 12" src="https://user-images.githubusercontent.com/68572707/139477169-3197ef6b-3869-46bc-afd8-99c6e56d8b70.png">

What happens if the user sets a formatted date inexistent? 
Could be a solution to set a date picker option on the columns array?

**Comment by cmbirk** [comment]
I think we should use the default html element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

We don't want to start introducing a lot of custom components at this point, but should revisit in the future to override the default html component if a user wishes
